import com.google.common.collect.ImmutableList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ImmutableList l = ImmutableList.of();
        System.out.println(new Main().getGreeting());
    }
}
